server:
  port: 6082
spring:
  application:
    name: damai-user-service
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-user-${spring.profiles.active}.yaml
  jackson:
    generator:
      write-numbers-as-strings: true
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      database: 0
      host: 192.168.88.130
      port: 6379
      timeout: 3000
  cloud:
    nacos:
      server-addr: 192.168.88.130:8848
      username: nacos
      password: nacos
    openfeign:
      okhttp:
        enabled: true
bloom-filter:
  name: user-register-bloom-filter
  expectedInsertions: 1000
  falseProbability: 0.01

aj:
  captcha:
    cache-type: redis
    type: default
    water-mark: \u6211\u7684\u6C34\u5370
    slip-offset: 5
    aes-status: true
    interference-options: 2
    font-style: 1
    font-size: 25
    history-data-clear-enable: false
    req-frequency-limit-enable: false
    req-get-lock-limit: 5
    req-get-lock-seconds: 360
    req-get-minute-limit: 30
    req-check-minute-limit: 30

management:
  health:
    elasticsearch:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.damai.controller
#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: false
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true